// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwDH7pBa6v_P_A5sCSnyuLEIRhNfPSZoU',
    appId: '1:594685359786:web:1ac8d639999218e766c2d3',
    messagingSenderId: '594685359786',
    projectId: 'mega-mind-iot',
    authDomain: 'mega-mind-iot.firebaseapp.com',
    databaseURL: 'https://mega-mind-iot-default-rtdb.firebaseio.com',
    storageBucket: 'mega-mind-iot.appspot.com',
    measurementId: 'G-3EZJ9BEW7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSOoAHh9tG7x90MeC8h14GczWQZNUF43U',
    appId: '1:594685359786:android:80d6a521695d621266c2d3',
    messagingSenderId: '594685359786',
    projectId: 'mega-mind-iot',
    databaseURL: 'https://mega-mind-iot-default-rtdb.firebaseio.com',
    storageBucket: 'mega-mind-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBawVc3DQew6evxZRM0424cVTfpGxOzqGQ',
    appId: '1:594685359786:ios:a33526365daa52ae66c2d3',
    messagingSenderId: '594685359786',
    projectId: 'mega-mind-iot',
    databaseURL: 'https://mega-mind-iot-default-rtdb.firebaseio.com',
    storageBucket: 'mega-mind-iot.appspot.com',
    androidClientId: '594685359786-c3t0erio42isnopvlhlhjr597tf09qei.apps.googleusercontent.com',
    iosClientId: '594685359786-pqelme3ug588r2mrrlfbgrlls6jjhi77.apps.googleusercontent.com',
    iosBundleId: 'ai.megamind.yobo.yoboBot',
  );
}
